auth = "plain[passwd=/etc/ocserv/ocpasswd]"

tcp-port = 443
udp-port = 443

run-as-user = nobody
run-as-group = nogroup

socket-file = /run/ocserv-socket

server-cert = /etc/ocserv/server-cert.pem
server-key = /etc/ocserv/server-key.pem

max-clients = 1024
max-same-clients = 1

keepalive = 32400
dpd = 90
mobile-dpd = 1800

try-mtu-discovery = true

device = vpns

ipv4-network = 10.10.10.0
ipv4-netmask = 255.255.255.0

dns = 1.1.1.1
dns = 8.8.8.8

route = default

cisco-client-compat = true
