#!/usr/bin/env bash

set -Eeuo pipefail

BASE_DIR="/opt/l-panel/cli"

source "$BASE_DIR/lib/colors.sh"
source "$BASE_DIR/lib/common.sh"
source "$BASE_DIR/lib/version.sh"

while true
do

show_header

echo "1) Install L-Panel"
echo "2) Install Ocserv 1.5.0"
echo "3) Update L-Panel"
echo "4) Uninstall L-Panel"
echo "0) Exit"

echo

read -rp "Select: " OPTION

case "$OPTION" in

1)

    bash "$BASE_DIR/commands/install.sh"

;;

2)

    bash "$BASE_DIR/commands/ocserv.sh"

;;

3)

    bash "$BASE_DIR/commands/update.sh"

;;

4)

    bash "$BASE_DIR/commands/uninstall.sh"

;;

0)

    clear
    exit

;;

*)

    fail "Invalid Option"

    sleep 2

;;

esac

done
