CREATE TABLE admins (

id INT AUTO_INCREMENT PRIMARY KEY,

username VARCHAR(100) UNIQUE NOT NULL,

password VARCHAR(255) NOT NULL,

role VARCHAR(50) DEFAULT 'admin',

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
