ALTER TABLE users
ADD COLUMN IF NOT EXISTS traffic_limit BIGINT DEFAULT 0;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS used_traffic BIGINT DEFAULT 0;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS server_id INTEGER;
