auth = "plain[/etc/ocserv/ocpasswd]"

tcp-port = 443
udp-port = 443

run-as-user = nobody
run-as-group = nobody

socket-file = /run/ocserv-socket

max-clients = 100
max-same-clients = 2

server-cert = /etc/ocserv/server-cert.pem
server-key = /etc/ocserv/server-key.pem

ipv4-network = 10.10.10.0
ipv4-netmask = 255.255.255.0

dns = 1.1.1.1
dns = 8.8.8.8

default-domain = vpn

route = default

device = vpns

compression = true

keepalive = 32400

dpd = 90

mobile-dpd = 1800

log-file = /var/log/ocserv.log
